### PR TITLE
added auto advance settings state and slider

### LINKED ISSUE #3: [Feature Request] Dynamic interval for auto advance mode
**Is your feature request related to a problem? Please describe.**

Possibility to set a time interval for "auto advance" mode.

It would be interesting that the user can only change the slider if the auto-advance mode is enabled

**Describe the solution you'd like**

For example, create an slider below the auto advance toggle, to select the time between each word.

image

E.g: [Material UI Slider](https://mui.com/material-ui/react-slider/)

image

### PR DESCRIPTION
**Pull request by ewatch**
# Description

This PR adds the slider to the settings modal. Additional it adds the state to the SettingsContext to be used in the App for controlling the speed of change to jump to the next word.

Fixes #3 

## Type of change

Please delete options that are not relevant.

- [ ] Correction on an existing word
- [ ] New word (translation, image, phrase)
- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Documentation (non-breaking change that updates the documentation)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

By running the application enabling / disabling auto advance and changing the interval back and forth.

## Checklist:

- [x] I have read the [Contribution Guidelines](https://github.com/sbplat/Macro-API/blob/main/CONTRIBUTING.md) and [Code of Conduct](https://github.com/sbplat/Macro-API/blob/main/CODE_OF_CONDUCT.md)
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] Consider giving a ⭐ if you enjoy the project

### CODE REVIEW

**Comment by ewatch** [comment]
Can't see what the problem is, @mathiasfc can please show the error message ?

**Comment by mathiasfc** [comment]
> Can't see what the problem is, @mathiasfc can please show the error message ?

Sure, 
image

Maybe you can see the error running: `npm run type-check` or `npm run lint` :thinking:

**Comment by ewatch** [comment]
@mathiasfc Thank you for posting the error message, didn't think about running the linting locally, sorry.
Okay i think I fixed the issues. Please propose a better fix if it's not acceptable for the ReactChange Event handler.

**Comment by ewatch** [comment]
@mathiasfc would be great if this could be reviewed and merged

**Review by mathiasfc — APPROVED** [review]

**Pull request merged**
